### ISSUE TITLE
No such file or directory: 'numbead_predictor.gz'

### ISSUE THREAD

**Issue by ljmartin** [marrink-lab/cartographer#1]
Hi Marrink-lab,
I'd love to test this tool out but it's missing a file, numbead_predictor.gz (loaded by `clf = joblib.load(FILENAME)`). I know the readme says not to expect anything functional, but are you open to sharing a copy please? 
Thanks!

**Comment by pckroon** [comment]
Hi,

I currently don't have anything I can share, sorry. I have a version that works locally (with different than what's posted here), but that's not in a shareable state. Besides that, it only creates mappings at the moment, not full topologies.
Drop me an email for further discussion :)
